Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@mnhsaki 
mnhsaki
/
async
Public
1
00
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
l CI #14
Summary
Workflow file
Jobs
deploy
Workflow file for this run
.github/workflows/test.yml at 3c14e55
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          
            cd /var/www/html/async/
            git checkout main
            git pull origin main
